### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mdodar** [KristofferC/Phon#11]
hi Kristoffer
I installed phon on python 2.7. when I want to run I face this error

>>> from phon.io.read.read_from_abaqus_inp import read_from_abaqus_inp
>>> from phon.mesh_tools.create_cohesive_elements import create_cohesive_elements
>>> from phon.io.write.export_to_abaqus import export_to_abaqus
>>> mesh=read_from_abaqus_inp("40.inp")
>>> create_cohesive_elements(mesh, mesh_dimension=3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/phon/mesh_tools/create_cohesive_elements.py", line 60, in create_cohesive_elements
  File "build/bdist.linux-x86_64/egg/phon/mesh_tools/create_cohesive_elements.py", line 331, in get_node_id_grain_lut
KeyError: 9818

What is the source for this problem?

**Comment by KristofferC** [comment]
Please post your .inp file so I can try it.

**Comment by mdodar** [comment]
Dear Kristoffer,
I realized it has problems with "hex" mesh type. For 'tet' mesh type it works properly. 

[grain.inp.txt](https://github.com/KristofferC/Phon/files/295836/grain.inp.txt)
Regards,
Mohammad

**Comment by KristofferC** [comment]
This is a bug in Neper for hex elements. 

From your inp file:

```
*Element, type=C3D8
1, 1, 2, 11, 10, 445, 446, 455, 454
```

The elements here should start not be restarted to `1`. Until Neper is fixed you have to fix this somehow yourself so that the element numbers continue from the previous section.
