### ISSUE TITLE
Having trouble on generating cohesive element

### ISSUE THREAD

**Issue by dutblue** [KristofferC/Phon#21]
Dear Kristoffer
Thank you for doing a fabulous job on this useful software. But since I use neper 3.0.2, the command -dim all can't be used any more, it was replaced by -dim 3. So if I use commend like "neper -M n2500.tess -elt hex -dim 3 -format inp", I can't get any cohesive element. Would mind help me to figure this out? Thank you so much!
yours sincerely fan

**Comment by KristofferC** [comment]
Neper 3 can create cohesive elements by itself. Perhaps you can use that?

**Comment by KristofferC** [comment]
I tried today with neper 3.0.2 and had no problems:

```
./neper -T -n 2
./neper -M n2-id1.tess -dim all -format inp
```

**Comment by dutblue** [comment]
Wow, thank you Kris! I've already fixed it! Still thank you for ur contribution! Have a nice day:)
