### ISSUE TITLE
2D Meshing 

### ISSUE THREAD

**Issue by jaydeshpande** [KristofferC/Phon#6]
Hello Mr. Carlsson, 

I tried the new version of neper (neutral), following are the things that I noticed while using neper for 2D case.
1. Creating Tessellations : neper -T -n 100 -id 1 -dim 2 -reg 1 -filter size 
2. Creating Mesh : neper -M n100-id1.tess -dim 1,2 -format 'inp' -faset 'faces'
while creating Mesh -nset all command doesn't work, it stops the code. 

I followed similar procedure for 3D and it works fine, it doesn't seem to work properly for 2D case. Could you tell possible cause for the error? Or as I read in another reported issue, it doesn't support 2D yet? 

Thanks,
Jaydeep

**Comment by KristofferC** [comment]
cohesive elements for 2D is supported but making them have a finite thickness is not yet.

Did you remember to put the correct mesh dimension for the method like this:
```python
create_cohesive_elements(self.mesh, 3)
```

If it still does not work, could you give a link to the .inp file you get from neper?

**Comment by jaydeshpande** [comment]
Thanks for the reply, I tried varying the mesh size, still I'm getting the same error: 
73         grain_id_1 = grains_connected_to_face[0]
74         grain_id_2 = grains_connected_to_face[1]

Link to inp file: https://drive.google.com/file/d/0B3gnGWlJ1s80amkyUTNZdExLYkk/view?usp=sharing

I know something is wrong with -nset or creating the proper sets of adjacent grains. I am not able to figure out where it is going wrong. 

Thanks, 
Jaydeep

**Comment by KristofferC** [comment]
I used your .inp file and it seems to work for me:

![](http://i.imgur.com/mlKQBOE.png)

This is the exact commands I am using:

```python
from phon.io.read.read_from_neper_inp import read_from_neper_inp
from phon.io.write.export_to_abaqus import export_to_abaqus
from phon.mesh_tools.create_cohesive_elements import create_cohesive_elements

inputfile = "n100-id1.inp"
mesh = read_from_neper_inp(inputfile, verbose=0)
create_cohesive_elements(mesh, 2)
export_to_abaqus("n100-id1_coh.inp", mesh, write_2d_elements=True)
```

If you do that, does it work? Do you have newest Phon?

**Comment by jaydeshpande** [comment]
Thank you so much Mr. Carlsson, it works. I was not using the other arguments from export_to_abaqus. Thank you for prompt replies and the support. I thank you once again for developing and making the tool open source.

**Comment by KristofferC** [comment]
I am glad it worked.

The `write_2d_elements` argument to  `export_to_abaqus` is a bit weird. It is mostly a leftover from when I started writing Phon and it was only used for 3D.

I will try think of a way for situations like this to not happen again. Maybe give an error message when 0 elements are written by `export_to_abaqus` or something.

**Comment by Shahriortsr** [comment]
Hi, I am trying to visualize the deformed grain. Is there any way that I can visualize it from the abaqus odb file? I used neper to visualize the undeformed grains while creating the inp file. Thanks and sorry to interrupt in this discussion.

**Comment by swapz01** [comment]
Is it possible to make a quad mesh in 2d cell grain wise nonuniformly?
PFA for reference
![IMG_20190625_143746-min](https://user-images.githubusercontent.com/52198346/60087646-0993a580-975b-11e9-86e5-3e78255a8a76.jpg)
can u give me the commands to generate such a mesh.
Thank you.
