### ISSUE TITLE
Query about zero thickness cohesive element 

### ISSUE THREAD

**Issue by mrzhaojyi** [KristofferC/Phon#7]
Hi, Mr.KristofferC

           I am testing the cohesive element in abaqus. However I really don't know how to using the 2-D zero thickness cohesive element in CPFEM. Each time I run the abaqus job, there is a error: "The geometry of 69 elements is too distorted" no matter how small my load. And I checked the message file, it says : 
***ERROR: ELEMENT 670 INSTANCE TESS-1 IS HIGHLY DISTORTED

 ***WARNING: THE LENGTH OF ELEMENT 670 INSTANCE TESS-1 IS EQUAL TO OR SMALLER 
             THAN ZERO
          Could you give me some advice about how to deal with this problem?  I think it should be ok to use zero thickness in the inp file modelling but I really can't figure this problem. 

Best regards
Jingyi

**Comment by KristofferC** [comment]
Hmm, that's strange. Can you post the .inp file you send into Phon (unless it is huge) and I will try see what is wrong.

**Comment by mrzhaojyi** [comment]
This is a input file to test the 2D boundary. The bottom is fixed and a
small disp is applied on the top. For simplify, I just use homogeneous
material install of using a UMAT.

**Comment by mrzhaojyi** [comment]
I finally found the reason : The material properties for grain boundary is not correct. And the 0-thickness cohesive element must be treated carefully.

**Comment by KristofferC** [comment]
Sorry for being unhelpful. I have been very busy lately with a course and other things. Glad you got it to work :+1:
